model_list:
  - model_name: ai-angelo-zero
    litellm_params:
      model: ollama/llama3.2
      api_base: "http://host.docker.internal:11434"
      drop_params: True # added this line to suport base64